application: proyecto
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  script: handlers.main.app

- url: /tareas/nueva
  script: handlers.Tareas.nueva.app

- url: /tareas/elimina
  script: handlers.Tareas.elimina.app

- url: /tareas/modifica
  script: handlers.Tareas.modifica.app

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: "latest"
